language: dart
sudo: false
dart:
  - stable
  - dev

services:
  - docker

before_script:
  - mkdir kuzzle-docker
  - cd kuzzle-docker
  - wget http://kuzzle.io/docker-compose.yml
  - sysctl -w vm.max_map_count=262144
  - docker-compose up -d
  - until curl "http://localhost:7512/?pretty"; do sleep 10; done
  - cd ../
  - ./adminauth.sh
  - pub get

script:
  - dartanalyzer lib test --fatal-warnings
  - pub run test
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - dartdoc

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/api
  on:
    branch: master
    condition: $TRAVIS_DART_VERSION=stable