language: dart
sudo: false
dart: dev

services:
  - docker

before_script:
  - mkdir kuzzle-docker
  - cd kuzzle-docker
  - wget http://kuzzle.io/docker-compose.yml
  - sysctl -w vm.max_map_count=262144
  - docker-compose up -d
  - until curl "http://localhost:7512/?pretty"; do sleep 10; done
  - cd ../
  - ./adminauth.sh
  - pub global activate coverage

script:
  - dartanalyzer lib test --fatal-warnings
  - pub run test
  - mkdir coverage
  - dart --pause-isolates-on-exit --enable_asserts --enable-vm-service test/.test_coverage.dart &
  - sleep 10
  - pub global run coverage:collect_coverage --uri=http://127.0.0.1:8181 -o coverage/coverage.json --resume-isolates
  - pub global run coverage:format_coverage -l --packages=/home/prijindal/projects/kuzzle_dart/.packages -i coverage/coverage.json --report-on=lib -o coverage/lcov.info

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - dartdoc

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/api
  on:
    branch: master