name: kuzzle
version: 0.0.1

description: A library to communicate with kuzzle API
author: Priyanshu Jindal<priyanshujindal1995@gmail.com>
homepage: https://github.com/prijindal/kuzzle_dart

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  geohash: any
  pedantic: any
  uuid: any
  web_socket_channel: any

dev_dependencies:
  test: any
  coverage: any
