name: kuzzle
version: 1.0.0-alpha.4

description: A library to interact with kuzzle API. A backend software, self-hostable and ready to use to power modern cross-platform apps.
authors:
- Priyanshu Jindal<priyanshujindal1995@gmail.com>
- Sacha Stafyniak<sacha.stafyniak@gmail.com>
homepage: https://github.com/prijindal/kuzzle_dart

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  pedantic: ^1.4.0
  meta: ^1.1.6
  uuid: ^1.0.3

dev_dependencies:
  test: ^1.5.1+1
  coverage: ^0.12.3
